run-dist:
	./gradlew installDist
	./build/install/app/bin/app

build:
	./gradlew build

clean:
	./gradlew clean

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

lint:
	./gradlew check

.PHONY: build clean test report lint run-dist
